-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2021-11-24 19:56:39.459

-- tables
-- Table: AspNetRoleClaims
CREATE TABLE AspNetRoleClaims (
    Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    RoleId text  NOT NULL,
    ClaimType text  NOT NULL,
    ClaimValue text  NOT NULL,
    CONSTRAINT AspNetRoleClaims_pk PRIMARY KEY (Id)
);

-- Table: AspNetRoles
CREATE TABLE AspNetRoles (
    Id text  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    Name varchar(256)  NOT NULL,
    NormalizedName varchar(256)  NOT NULL,
    ConcurrencyStamp text  NOT NULL,
    CONSTRAINT AspNetRoles_pk PRIMARY KEY (Id)
);

-- Table: AspNetUserClaims
CREATE TABLE AspNetUserClaims (
    Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    UserId text  NOT NULL,
    ClaimType text  NOT NULL,
    ClaimValue text  NOT NULL,
    CONSTRAINT AspNetUserClaims_pk PRIMARY KEY (Id)
);

-- Table: AspNetUserLogins
CREATE TABLE AspNetUserLogins (
    LoginProvider varchar(128)  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ProviderKey varchar(128)  NOT NULL,
    ProviderDisplayName text  NOT NULL,
    UserId text  NOT NULL,
    CONSTRAINT AspNetUserLogins_pk PRIMARY KEY (LoginProvider,ProviderKey)
);

-- Table: AspNetUserRoles
CREATE TABLE AspNetUserRoles (
    UserId text  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    RoleId text  NOT NULL,
    CONSTRAINT AspNetUserRoles_pk PRIMARY KEY (UserId,RoleId)
);

-- Table: AspNetUserTokens
CREATE TABLE AspNetUserTokens (
    UserId int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    LoginProvider int  NOT NULL,
    Name int  NOT NULL,
    Value int  NOT NULL,
    CONSTRAINT AspNetUserTokens_pk PRIMARY KEY (UserId,LoginProvider,Name)
);

-- Table: AspNetUsers
CREATE TABLE AspNetUsers (
    Id text  NOT NULL,
    UserName varchar(256)  NOT NULL,
    NormalizedUserName varchar(256)  NOT NULL,
    Email varchar(256)  NOT NULL,
    NormalizedEmail varchar(256)  NOT NULL,
    EmailConfirmed boolean  NOT NULL,
    PasswordHash text  NOT NULL,
    SecurityStamp text  NOT NULL,
    ConcurrencyStamp text  NOT NULL,
    PhoneNumber text  NOT NULL,
    PhoneNumberConfirmed boolean  NOT NULL,
    TwoFactorEnabled boolean  NOT NULL,
    LockoutEnd timestamp  NOT NULL,
    LockoutEnabled boolean  NOT NULL,
    AccessFailedCount int  NOT NULL,
    schedule_id int  NOT NULL,
    AspNetUserTokens_UserId int  NOT NULL,
    AspNetUserTokens_LoginProvider int  NOT NULL,
    AspNetUserTokens_Name int  NOT NULL,
    addres_id int  NOT NULL,
    CONSTRAINT AspNetUsers_pk PRIMARY KEY (Id)
);

-- Table: addres
CREATE TABLE addres (
    id int  NOT NULL,
    city_id int  NOT NULL,
    zip_code varchar(10)  NOT NULL,
    addres varchar(100)  NOT NULL,
    country_id int  NOT NULL,
    CONSTRAINT addres_pk PRIMARY KEY (id)
);

-- Table: category
CREATE TABLE category (
    id int  NOT NULL,
    name varchar(50)  NOT NULL,
    CONSTRAINT category_pk PRIMARY KEY (id)
);

-- Table: city
CREATE TABLE city (
    id int  NOT NULL,
    name text  NOT NULL,
    country_id int  NOT NULL,
    CONSTRAINT city_pk PRIMARY KEY (id)
);

-- Table: country
CREATE TABLE country (
    id int  NOT NULL,
    name text  NOT NULL,
    CONSTRAINT country_pk PRIMARY KEY (id)
);

-- Table: images
CREATE TABLE images (
    id int  NOT NULL,
    name varchar(100)  NOT NULL,
    absolute_path varchar(256)  NOT NULL,
    mime_type varchar(64)  NOT NULL,
    last_update date  NOT NULL,
    create_date date  NOT NULL,
    CONSTRAINT images_pk PRIMARY KEY (id)
);

-- Table: offers
CREATE TABLE offers (
    Id int  NOT NULL,
    author text  NOT NULL,
    title varchar(256)  NOT NULL,
    content text  NOT NULL,
    date_gmt date  NOT NULL,
    is_active boolean  NOT NULL,
    CONSTRAINT offers_pk PRIMARY KEY (Id)
);

-- Table: offersCategory
CREATE TABLE offersCategory (
    id int  NOT NULL,
    offers_Id int  NOT NULL,
    category_id int  NOT NULL,
    CONSTRAINT offersCategory_pk PRIMARY KEY (id)
);

-- Table: offersCities
CREATE TABLE offersCities (
    id int  NOT NULL,
    city_id int  NOT NULL,
    offer_id int  NOT NULL,
    CONSTRAINT offersCities_pk PRIMARY KEY (id)
);

-- Table: offersSchedule
CREATE TABLE offersSchedule (
    id int  NOT NULL,
    offers_Id int  NOT NULL,
    schedule_id int  NOT NULL,
    CONSTRAINT offersSchedule_pk PRIMARY KEY (id)
);

-- Table: reviews
CREATE TABLE reviews (
    id int  NOT NULL,
    author text  NOT NULL,
    title varchar(256)  NOT NULL,
    content text  NOT NULL,
    rating smallint  NOT NULL,
    offer int  NOT NULL,
    review_date_gmt date  NOT NULL,
    CONSTRAINT reviews_pk PRIMARY KEY (id)
);

-- Table: schedule
CREATE TABLE schedule (
    id int  NOT NULL,
    start_date date  NOT NULL,
    end_date date  NOT NULL,
    client_id text  NOT NULL,
    last_update date  NOT NULL,
    CONSTRAINT schedule_pk PRIMARY KEY (id)
);

-- foreign keys
-- Reference: AspNetRoleClaims_AspNetRoles (table: AspNetRoleClaims)
ALTER TABLE AspNetRoleClaims ADD CONSTRAINT AspNetRoleClaims_AspNetRoles
    FOREIGN KEY (RoleId)
    REFERENCES AspNetRoles (Id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: AspNetUserClaims_AspNetUsers (table: AspNetUserClaims)
ALTER TABLE AspNetUserClaims ADD CONSTRAINT AspNetUserClaims_AspNetUsers
    FOREIGN KEY (UserId)
    REFERENCES AspNetUsers (Id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: AspNetUserLogins_AspNetUsers (table: AspNetUserLogins)
ALTER TABLE AspNetUserLogins ADD CONSTRAINT AspNetUserLogins_AspNetUsers
    FOREIGN KEY (UserId)
    REFERENCES AspNetUsers (Id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: AspNetUserRoles_AspNetRoles (table: AspNetUserRoles)
ALTER TABLE AspNetUserRoles ADD CONSTRAINT AspNetUserRoles_AspNetRoles
    FOREIGN KEY (RoleId)
    REFERENCES AspNetRoles (Id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: AspNetUserRoles_AspNetUsers (table: AspNetUserRoles)
ALTER TABLE AspNetUserRoles ADD CONSTRAINT AspNetUserRoles_AspNetUsers
    FOREIGN KEY (UserId)
    REFERENCES AspNetUsers (Id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: AspNetUsers_AspNetUserTokens (table: AspNetUsers)
ALTER TABLE AspNetUsers ADD CONSTRAINT AspNetUsers_AspNetUserTokens
    FOREIGN KEY (AspNetUserTokens_UserId, AspNetUserTokens_LoginProvider, AspNetUserTokens_Name)
    REFERENCES AspNetUserTokens (UserId, LoginProvider, Name)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: AspNetUsers_addres (table: AspNetUsers)
ALTER TABLE AspNetUsers ADD CONSTRAINT AspNetUsers_addres
    FOREIGN KEY (addres_id)
    REFERENCES addres (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: AspNetUsers_schedule (table: schedule)
ALTER TABLE schedule ADD CONSTRAINT AspNetUsers_schedule
    FOREIGN KEY (client_id)
    REFERENCES AspNetUsers (Id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: addres_city (table: addres)
ALTER TABLE addres ADD CONSTRAINT addres_city
    FOREIGN KEY (city_id)
    REFERENCES city (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: addres_country (table: addres)
ALTER TABLE addres ADD CONSTRAINT addres_country
    FOREIGN KEY (country_id)
    REFERENCES country (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: city_country (table: city)
ALTER TABLE city ADD CONSTRAINT city_country
    FOREIGN KEY (country_id)
    REFERENCES country (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: offersCities_city (table: offersCities)
ALTER TABLE offersCities ADD CONSTRAINT offersCities_city
    FOREIGN KEY (city_id)
    REFERENCES city (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: offersCities_offers (table: offersCities)
ALTER TABLE offersCities ADD CONSTRAINT offersCities_offers
    FOREIGN KEY (offer_id)
    REFERENCES offers (Id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: offersSchedule_offers (table: offersSchedule)
ALTER TABLE offersSchedule ADD CONSTRAINT offersSchedule_offers
    FOREIGN KEY (offers_Id)
    REFERENCES offers (Id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: offersSchedule_schedule (table: offersSchedule)
ALTER TABLE offersSchedule ADD CONSTRAINT offersSchedule_schedule
    FOREIGN KEY (schedule_id)
    REFERENCES schedule (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: offert_category_category (table: offersCategory)
ALTER TABLE offersCategory ADD CONSTRAINT offert_category_category
    FOREIGN KEY (category_id)
    REFERENCES category (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: offert_category_offers (table: offersCategory)
ALTER TABLE offersCategory ADD CONSTRAINT offert_category_offers
    FOREIGN KEY (offers_Id)
    REFERENCES offers (Id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: reviews_AspNetUsers (table: reviews)
ALTER TABLE reviews ADD CONSTRAINT reviews_AspNetUsers
    FOREIGN KEY (author)
    REFERENCES AspNetUsers (Id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: reviews_offers (table: reviews)
ALTER TABLE reviews ADD CONSTRAINT reviews_offers
    FOREIGN KEY (offer)
    REFERENCES offers (Id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- End of file.

