-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2021-11-17 20:32:43.234

-- tables
-- Table: AspNetRoleClaims
CREATE TABLE AspNetRoleClaims (
    Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    RoleId text  NOT NULL,
    ClaimType text  NOT NULL,
    ClaimValue text  NOT NULL,
    CONSTRAINT AspNetRoleClaims_pk PRIMARY KEY (Id)
);

-- Table: AspNetRoles
CREATE TABLE AspNetRoles (
    Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    Name varchar(256)  NOT NULL,
    NormalizedName varchar(256)  NOT NULL,
    ConcurrencyStamp text  NOT NULL,
    CONSTRAINT AspNetRoles_pk PRIMARY KEY (Id)
);

-- Table: AspNetUserClaims
CREATE TABLE AspNetUserClaims (
    Id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    UserId text  NOT NULL,
    ClaimType text  NOT NULL,
    ClaimValue text  NOT NULL,
    CONSTRAINT AspNetUserClaims_pk PRIMARY KEY (Id)
);

-- Table: AspNetUserLogins
CREATE TABLE AspNetUserLogins (
    LoginProvider varchar(128)  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ProviderKey varchar(128)  NOT NULL,
    ProviderDisplayName text  NOT NULL,
    UserId text  NOT NULL,
    CONSTRAINT AspNetUserLogins_pk PRIMARY KEY (LoginProvider,ProviderKey)
);

-- Table: AspNetUserRoles
CREATE TABLE AspNetUserRoles (
    UserId text  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    RoleId text  NOT NULL,
    CONSTRAINT AspNetUserRoles_pk PRIMARY KEY (UserId,RoleId)
);

-- Table: AspNetUserTokens
CREATE TABLE AspNetUserTokens (
    UserId int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    LoginProvider int  NOT NULL,
    Name int  NOT NULL,
    Value int  NOT NULL,
    CONSTRAINT AspNetUserTokens_pk PRIMARY KEY (UserId,LoginProvider,Name)
);

-- Table: AspNetUsers
CREATE TABLE AspNetUsers (
    Id text  NOT NULL,
    UserName varchar(256)  NOT NULL,
    NormalizedUserName varchar(256)  NOT NULL,
    Email varchar(256)  NOT NULL,
    NormalizedEmail varchar(256)  NOT NULL,
    EmailConfirmed boolean  NOT NULL,
    PasswordHash text  NOT NULL,
    SecurityStamp text  NOT NULL,
    ConcurrencyStamp text  NOT NULL,
    PhoneNumber text  NOT NULL,
    PhoneNumberConfirmed boolean  NOT NULL,
    TwoFactorEnabled boolean  NOT NULL,
    LockoutEnd timestamp  NOT NULL,
    LockoutEnabled boolean  NOT NULL,
    AccessFailedCount int  NOT NULL,
    CONSTRAINT AspNetUsers_pk PRIMARY KEY (Id)
);

-- Table: addres
CREATE TABLE addres (
    id int  NOT NULL,
    city int  NOT NULL,
    zip_code varchar(10)  NOT NULL,
    addres varchar(100)  NOT NULL,
    country int  NOT NULL,
    CONSTRAINT addres_pk PRIMARY KEY (id)
);

-- Table: images
CREATE TABLE images (
    id int  NOT NULL,
    name varchar(100)  NOT NULL,
    absolute_path varchar(256)  NOT NULL,
    mime_type varchar(64)  NOT NULL,
    last_update date  NOT NULL,
    create_date date  NOT NULL,
    CONSTRAINT images_pk PRIMARY KEY (id)
);

-- Table: offers
CREATE TABLE offers (
    Id int  NOT NULL,
    author int  NULL,
    title varchar(256)  NOT NULL,
    content text  NOT NULL,
    date_gmt date  NOT NULL,
    is_active boolean  NOT NULL,
    CONSTRAINT offers_pk PRIMARY KEY (Id)
);

-- Table: reviews
CREATE TABLE reviews (
    id int  NOT NULL,
    author int  NULL,
    title varchar(256)  NOT NULL,
    content text  NOT NULL,
    rating smallint  NULL,
    offer int  NOT NULL,
    review_date_gmt date  NOT NULL,
    CONSTRAINT offer UNIQUE () NOT DEFERRABLE  INITIALLY IMMEDIATE,
    CONSTRAINT reviews_pk PRIMARY KEY (id)
);

-- Table: schedule
CREATE TABLE schedule (
    id int  NOT NULL,
    offer_id int  NULL,
    start_date date  NOT NULL,
    end_date date  NOT NULL,
    client_id int  NOT NULL,
    last_update date  NOT NULL,
    CONSTRAINT schedule_pk PRIMARY KEY (id)
);

-- End of file.

